app = 'worldfront-server'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'

[env]
  GAME_ENV = 'dev'
  NUM_WORKERS = '2'
  TURNSTILE_SITE_KEY = '1x00000000000000000000AA'
  API_KEY = 'WARNING_DEV_API_KEY_DO_NOT_USE_IN_PRODUCTION'
  ADMIN_BOT_API_KEY = 'WARNING_DEV_ADMIN_BOT_KEY_DO_NOT_USE_IN_PRODUCTION'
  INSTANCE_ID = 'WORLDFRONT'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
